# Generated by Django 2.2.12 on 2021-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=5, null=True, verbose_name='病人性别')),
                ('age', models.CharField(blank=True, max_length=10, null=True, verbose_name='病人年龄')),
                ('position', models.CharField(max_length=20, verbose_name='影像部位')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='账户')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
            ],
        ),
    ]
