# Generated by Django 2.2.12 on 2021-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeAnnotation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_annotation', models.CharField(blank=True, max_length=100, null=True, verbose_name='自动标注结果')),
                ('manual_annotation', models.CharField(blank=True, max_length=100, null=True, verbose_name='手动标注结果')),
            ],
        ),
    ]
